import { NgModule } from "@angular/core";

import {
    AnimationDirective,
    AutofocusDirective,
    ChangeDirective,
    ClearableDirective,
    FocusableDirective,
    FormControlCheckable,
    FormControlColorPicker,
    FormControlInput,
    FormControlNumber,
    FormControlRadio,
    FormControlSelect,
    InputDirective,
    LoadableDirective,
    MutableDirective,
    OpenDirective,
    RemoveableDirective,
    RepositionableDirective,
    ResizableDirective,
    SelectableDirective,
    ShowableDirective,
} from "./directives";

@NgModule({
    exports: [
        AnimationDirective,
        AutofocusDirective,
        ChangeDirective,
        ClearableDirective,
        FocusableDirective,
        FormControlCheckable,
        FormControlColorPicker,
        FormControlInput,
        FormControlNumber,
        FormControlRadio,
        FormControlSelect,
        InputDirective,
        LoadableDirective,
        MutableDirective,
        OpenDirective,
        RemoveableDirective,
        RepositionableDirective,
        ResizableDirective,
        SelectableDirective,
        ShowableDirective,
    ],
    declarations: [
        AnimationDirective,
        AutofocusDirective,
        ChangeDirective,
        ClearableDirective,
        FocusableDirective,
        FormControlCheckable,
        FormControlColorPicker,
        FormControlInput,
        FormControlNumber,
        FormControlRadio,
        FormControlSelect,
        InputDirective,
        LoadableDirective,
        MutableDirective,
        OpenDirective,
        RemoveableDirective,
        RepositionableDirective,
        ResizableDirective,
        SelectableDirective,
        ShowableDirective,
    ],
})
export class ShoelaceStyleAngularModule {}
